name: update bins

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: |
          pip install requests
          pip install beautifulsoup4

      - name: run script
        run: python script.py

      - name: commit calendar
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add bins.ics
          git commit -m "update bins calendar" || exit 0
          git push
